use crate::ast::*;
use crate::generator::Generator;
use regex::escape;

pub fn generate_sort_command(
    generator: &mut Generator,
    cmd: &SimpleCommand,
    input_var: &str,
    command_index: &str,
) -> String {
    let output_var = format!("sort_output_{}", command_index);
    generate_sort_command_with_output(generator, cmd, input_var, command_index, &output_var)
}

pub fn generate_sort_command_with_output(
    generator: &mut Generator,
    cmd: &SimpleCommand,
    input_var: &str,
    command_index: &str,
    output_var: &str,
) -> String {
    let mut output = String::new();

    let mut numeric = false;
    let mut reverse = false;
    // Optional delimiter (-t CHAR) and key index (-k N)
    let mut delim_opt: Option<String> = None;
    let mut key_index_opt: Option<usize> = None;

    // Parse arguments conservatively. Accept combined shortopts (-nr) and separated forms.
    let mut i = 0usize;
    while i < cmd.args.len() {
        if let Word::Literal(arg_str, _) = &cmd.args[i] {
            if arg_str == "-n" {
                numeric = true;
            } else if arg_str == "-r" || arg_str == "r" {
                reverse = true;
            } else if arg_str == "-nr" || arg_str == "-rn" {
                numeric = true;
                reverse = true;
            } else if arg_str.starts_with("-t") {
                // -tCHAR or -t CHAR: capture CHAR possibly quoted
                let mut delim = arg_str[2..].to_string();
                if delim.is_empty() && i + 1 < cmd.args.len() {
                    if let Word::Literal(next_str, _) = &cmd.args[i + 1] {
                        delim = next_str.clone();
                        i += 1; // consume next
                    }
                }
                // Strip surrounding single or double quotes if present
                if delim.len() >= 2
                    && ((delim.starts_with('\'') && delim.ends_with('\''))
                        || (delim.starts_with('"') && delim.ends_with('"')))
                {
                    delim = delim[1..delim.len() - 1].to_string();
                }
                if !delim.is_empty() {
                    delim_opt = Some(delim);
                }
            } else if arg_str.starts_with("-k") {
                // -kN or -k N or -kN,M: take the leading N as key field
                let mut rest = arg_str[2..].to_string();
                if rest.is_empty() && i + 1 < cmd.args.len() {
                    if let Word::Literal(next_str, _) = &cmd.args[i + 1] {
                        rest = next_str.clone();
                        i += 1; // consume next
                    }
                }
                // Extract leading digits
                let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
                if !digits.is_empty() {
                    if let Ok(n) = digits.parse::<usize>() {
                        if n > 0 {
                            key_index_opt = Some(n - 1);
                        }
                    }
                }
            }
        }
        i += 1;
    }

    let input_ref = if input_var.starts_with('$') {
        input_var.to_string()
    } else {
        format!("${}", input_var)
    };
    output.push_str(&format!(
        "my @sort_lines_{} = split /\\n/msx, {};\n",
        command_index, input_ref
    ));
    if numeric {
        // Use an inline anonymous sort block to avoid named-sub collisions.
        // Each call to purify.pl / debashc starts with a fresh counter, so
        // named subs generated by different invocations can share the same
        // name and the last definition silently overrides the earlier ones.
        // Anonymous blocks have no name and therefore never collide.
        //
        // Choose split pattern based on -t delimiter if present
        let split_pat = if let Some(d) = &delim_opt {
            let esc = escape(d);
            generator.format_regex_pattern(&esc)
        } else {
            generator.format_regex_pattern(r"\s+")
        };
        let key_idx = key_index_opt.unwrap_or(0);
        // Accept integer or decimal numbers for numeric comparison. Trim
        // surrounding whitespace from the selected key field so values like
        // " 95.5" or "95.5 \t" are recognised as numbers.
        let num_re = generator.format_regex_pattern(r"^\d+(?:\.\d+)?$");
        output.push_str(&format!(
            "my @sort_sorted_{} = sort {{\n",
            command_index
        ));
        output.push_str(&format!("    my @a_fields = split {}, $a;\n", split_pat));
        output.push_str(&format!("    my @b_fields = split {}, $b;\n", split_pat));
        output.push_str("    my $a_num = 0;\n");
        output.push_str("    my $b_num = 0;\n");
        // Extract and trim the key fields conservatively.
        output.push_str(&format!(
            "    my $a_key = ( scalar @a_fields > {} ) ? $a_fields[{}] : q{{}}; $a_key =~ s/^\\s+|\\s+$//g;\n",
            key_idx, key_idx
        ));
        output.push_str(&format!(
            "    my $b_key = ( scalar @b_fields > {} ) ? $b_fields[{}] : q{{}}; $b_key =~ s/^\\s+|\\s+$//g;\n",
            key_idx, key_idx
        ));
        output.push_str(&format!(
            "    if ( $a_key =~ {} ) {{ $a_num = $a_key; }}\n",
            num_re
        ));
        output.push_str(&format!(
            "    if ( $b_key =~ {} ) {{ $b_num = $b_key; }}\n",
            num_re
        ));
        output.push_str("    $a_num <=> $b_num || $a cmp $b\n");
        output.push_str(&format!("}} @sort_lines_{};\n", command_index));
    } else if let Some(key_idx) = key_index_opt {
        // Non-numeric sort with a specific key field (-kN)
        let split_pat = if let Some(d) = &delim_opt {
            let esc = escape(d);
            generator.format_regex_pattern(&esc)
        } else {
            generator.format_regex_pattern(r"\s+")
        };
        output.push_str(&format!(
            "my @sort_sorted_{} = sort {{\n",
            command_index
        ));
        output.push_str(&format!("    my @a_fields = split {}, $a;\n", split_pat));
        output.push_str(&format!("    my @b_fields = split {}, $b;\n", split_pat));
        output.push_str(&format!(
            "    my $a_key = (scalar @a_fields > {}) ? $a_fields[{}] : q{{}};\n",
            key_idx, key_idx
        ));
        output.push_str(&format!(
            "    my $b_key = (scalar @b_fields > {}) ? $b_fields[{}] : q{{}};\n",
            key_idx, key_idx
        ));
        output.push_str("    $a_key cmp $b_key || $a cmp $b\n");
        output.push_str(&format!("}} @sort_lines_{};\n", command_index));
    } else {
        output.push_str(&format!(
            "my @sort_sorted_{} = sort @sort_lines_{};\n",
            command_index, command_index
        ));
    }
    if reverse {
        output.push_str(&format!(
            "@sort_sorted_{} = reverse @sort_sorted_{};\n",
            command_index, command_index
        ));
    }
    let output_name = output_var.trim_start_matches('$');
    let output_ref = if output_var.starts_with('$') {
        output_var.to_string()
    } else {
        format!("${}", output_name)
    };

    // Reuse an existing declaration when the caller already introduced this variable.
    if generator.declared_locals.contains(output_name) {
        output.push_str(&format!(
            "{} = join \"\\n\", @sort_sorted_{};\n",
            output_ref, command_index
        ));
    } else {
        output.push_str(&format!(
            "my {} = join \"\\n\", @sort_sorted_{};\n",
            output_ref, command_index
        ));
        generator.declared_locals.insert(output_name.to_string());
    }
    // Ensure output ends with newline to match shell behavior
    output.push_str(&generator.indent());
    output.push_str(&format!(
        "if ({} ne q{{}} && !({} =~ {})) {{\n",
        output_ref,
        output_ref,
        generator.newline_end_regex()
    ));
    generator.indent_level += 1;
    output.push_str(&generator.indent());
    output.push_str(&format!("{} .= \"\\n\";\n", output_ref));
    generator.indent_level -= 1;
    output.push_str(&generator.indent());
    output.push_str("}\n");

    // If this is being used in a pipeline context, assign the result back to the input variable
    if input_var != output_var {
        let output_input_ref = if input_var.starts_with('$') {
            input_var.to_string()
        } else {
            format!("${}", input_var)
        };
        output.push_str(&generator.indent());
        output.push_str(&format!("{} = {};\n", output_input_ref, output_ref));
    }

    output
}
