severity = 1
#BRUTAL!!!

#--------------------------------------------------------------
# I think these are really important, so always load them
[TestingAndDebugging::RequireUseStrict]
severity = 5
[TestingAndDebugging::RequireUseWarnings]
severity = 5
#--------------------------------------------------------------
# I think these are less important, so only load when asked
[Variables::ProhibitPackageVars]
severity = 2
[ControlStructures::ProhibitPostfixControls]
severity = cruel
# Same as "severity = 2"
#--------------------------------------------------------------
# I do not agree with these at all, so never load them
#
# I feel we can keep the same variable names as in the Bash script
[-NamingConventions::Capitalization]

#If the original bash script has magic number, may as well keep them?
[-ValuesAndExpressions::ProhibitMagicNumbers]

#If you are translation a tiny shell script add a "Version" would just be noise
#Anyway, how would we make up a "Version"?
[-Perl::Critic::Policy::Modules::RequireVersionVar]

#Requiring checks that "print" succeeds is a bit of overkill, I feel
#Also and Lex/Parse approach isn't well suited to inventing
#error handling code that doesn't exist in the original.
[-Perl::Critic::Policy::InputOutput::RequireCheckedSyscalls]
#--------------------------------------------------------------
# For all other Policies, I accept the default severity,
# so no additional configuration is required for them.
